version: '2'
services:
  rds-lb:
#    labels:
#      io.rancher.scheduler.affinity:host_label: stackType=auth
    tty: true
    image: rancher/lb-service-haproxy:v0.7.6
    stdin_open: true

  rds-link:
    image: rancher/external-service
