.catalog:
  name: "NHS Digital - CIS - URS OpenVPN"
  version: "0.1"
  description: |
    NHS Digital - CIS - URS OpenVPN
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "urs_version"
      description: "Which version of the OpenVPN is required to be deploy."
      label: "Version"
      required: true
      default: latest
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: 446537062602.dkr.ecr.eu-west-2.amazonaws.com/cishackday
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
