name: NHS Digital - CIS Externals OpenSSL
description: |
  Creates external dependencies needed by both the URS and Auth stacks. Contains Gluster, Directory, DB and PKI (OpenSSL)
version: 0.1
category: NHS-Digital
maintainer: NHS-Digital