.catalog:
  name: "NHS Digital - CIS - Externals OpenSSL"
  version: "0.1"
  description: |
    NHS Digital - CIS - Externals OpenSSL
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "externals_version"
      description: "Which version of the CIS Externals OpenSSL do you want to deploy?"
      label: "Version"
      required: true
      default: latest
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: 446537062602.dkr.ecr.eu-west-2.amazonaws.com/cishackday
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
    - variable: "urs_db_snapshot"
      description: "Please enter the ARN of the snapshot loaded into RDS"
      label: "RDS ARN"
      required: false
      default: 
      type: "string"
    - variable: "openssl_pki_password"
      description: "Please enter the OpenSSL Password"
      label: "OpenSSL PKI Password"
      required: true
      type: "string"
      default: "Password1"

    - variable: "priv_key_end"
      description: "Please enter the private key send date"
      label: "Private key end date"
      required: true
      type: "string"
      default: "20200117155000.0Z"
    - variable: "priv_key_start"
      description: "Please enter the private key start date"
      label: "Private key start date"
      required: true
      type: "string"
      default: "20180117162229.0Z"
    - variable: "aws_account_id"
      description: "Please enter the numeric AWS account ID"
      label: "AWS Account"
      required: true
      type: "string"
    - variable: "tag_name"
      description: "Please enter the tag name"
      label: "tag_name"
      required: true
      type: "string"

IAM-Database:
  scale: 1

Dir:
  scale: 1

OpenSSL-HTTP:
  scale: 1

Redis:
  scale: 1

Nfs:
  scale: 1

PKI-LDAP-LB:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: tcp
      service: OpenSSL-HTTP
      source_port: 389
      target_port: 10389
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate

